import type { StudioTemplate } from "@/features/studio/types";

/** Shown when `GET /api/catalog/templates` is empty or fails (dev / offline). */
export const FALLBACK_STUDIO_TEMPLATES: StudioTemplate[] = [
  {
    id: "cinematic_trailer",
    key: "cinematic_trailer",
    name: "Cinematic Trailer",
    description: "Epic widescreen beats, dramatic pacing, title-card energy.",
    category: "cinematic",
    defaultSceneCount: 6,
    defaultDurationSec: 20,
  },
  {
    id: "motivational_reel",
    key: "motivational_reel",
    name: "Motivational Reel",
    description: "Uplifting arc, fast cuts, inspiring voiceover-friendly pacing.",
    category: "social",
    defaultSceneCount: 5,
    defaultDurationSec: 30,
  },
  {
    id: "horror_story",
    key: "horror_story",
    name: "Horror Story",
    description: "Slow dread, harsh contrast, unsettling reveals.",
    category: "horror",
    defaultSceneCount: 6,
    defaultDurationSec: 30,
  },
  {
    id: "luxury_ad",
    key: "luxury_ad",
    name: "Luxury Ad",
    description: "Polished product hero shots, minimal motion, premium mood.",
    category: "commercial",
    defaultSceneCount: 4,
    defaultDurationSec: 20,
  },
  {
    id: "documentary",
    key: "documentary",
    name: "Documentary",
    description: "Observational framing, natural light, narrative clarity.",
    category: "documentary",
    defaultSceneCount: 6,
    defaultDurationSec: 60,
  },
  {
    id: "anime_sequence",
    key: "anime_sequence",
    name: "Anime Sequence",
    description: "Stylized motion, vibrant color, dynamic scene changes.",
    category: "anime",
    defaultSceneCount: 6,
    defaultDurationSec: 30,
  },
  {
    id: "social_reel",
    key: "social_reel",
    name: "Social Reel",
    description: "Vertical-friendly beats, punchy hooks, under 60 seconds.",
    category: "social",
    defaultSceneCount: 4,
    defaultDurationSec: 15,
  },
  {
    id: "product_promo",
    key: "product_promo",
    name: "Product Promo",
    description: "Feature highlights, clean backgrounds, CTA-ready ending.",
    category: "commercial",
    defaultSceneCount: 5,
    defaultDurationSec: 20,
  },
];
